import json

data = {
    0: "Thank You",
    1: "Incorrect Password",
    2: "Access Denied",
    3: "Invalid ID",
    4: "Please try again",
    5: "Dupicate ID",
    6: "The clock is flow",
    7: "The clock is full",
    8: "Duplicate finger",
    9: "Duplicated punch",
    10: "Beep kuko",
    11: "Beep siren",
    12: "-",
    13: "Beep bell",
    14: "-",
    15: "-",
    16: "-",
    17: "-",
    18: "Windows(R) opening sound",
    19: "-",
    20: "Fingerprint not emolt",
    21: "Password not emolt",
    22: "Badges not emolt",
    23: "Face not emolt",
    24: "Beep standard",
    25: "-",
    26: "-",
    27: "-",
    28: "-",
    29: "-",
    30: "Invalid user",
    31: "Invalid time period",
    32: "Invalid combination",
    33: "Illegal Access",
    34: "Disk space full",
    35: "Duplicate fingerprint",
    36: "Fingerprint not registered",
    37: "-",
    38: "-",
    39: "-",
    40: "-",
    41: "-",
    42: "-",
    43: "-",
    44: "-",
    45: "-",
    46: "-",
    47: "-",
    48: "-",
    49: "-",
    50: "-",
    51: "Focus eyes on the green box",
    52: "-",
    53: "-",
    54: "-",
    55: "-"
}


